Issue#12
Albermonte/Nimiq-Multi-Cashlink pull request #17
Opened 2021-05-04 18:02 UTC by onmax

Added formatter

2021-05-04 18:02 UTC, onmax commented
issue #14

2021-05-04 18:36 UTC, Albermonte approved these changes
Seems almost ok

2021-05-04 18:45 UTC, Albermonte requested changes
Lot of warnings on compile:
```
(!) Plugin svelte: Unused CSS selector ".ease"
src\modals\WordsModal.svelte
1101:   transition-duration: 150ms;
1102: }
1103:   .ease {
        ^
1104:   transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
1105: }
(!) Plugin svelte: Unused CSS selector ".ease-out"
src\modals\WordsModal.svelte
1104:   transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
1105: }
1106:   .ease-out {
        ^
1107:   transition-timing-function: cubic-bezier(0, 0, 0.2, 1);
1108: }
```
Pls, fix them

This pull doesn't fix the wrong sizes described [here](https://github.com/Albermonte/Nimiq-Multi-Cashlink/pull/14#issuecomment-830842264)
![image](https://user-images.githubusercontent.com/14013679/117053694-8d385900-ad19-11eb-9e0e-1009f9395e92.png)

2021-05-10 17:47 UTC, onmax commented
> Lot of warnings on compile:

TailwindCSS JIT mode seems not to be working properly

2021-05-10 18:37 UTC, Albermonte requested changes
![image](https://user-images.githubusercontent.com/14013679/117707957-7e491f00-b1cf-11eb-8dcc-fca8d9088741.png)

Same for every modal, something still broken :/

2026-07-31 11:33 UTC, closed without merging